package com.ghostlock.app;

import android.app.Dialog;
import android.content.Context;
import android.content.res.ColorStateList;
import android.graphics.drawable.GradientDrawable;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.core.content.ContextCompat;
import com.google.android.material.button.MaterialButton;

/** Primary Run action with themed confirmation and compatibility gating. */
public class ConfirmRunButton extends MaterialButton {
    private boolean confirmedClick;
    private boolean arranged;
    public ConfirmRunButton(Context context) { super(context); }
    public ConfirmRunButton(Context context, android.util.AttributeSet attrs) { super(context, attrs); }
    public ConfirmRunButton(Context context, android.util.AttributeSet attrs, int defStyleAttr) { super(context, attrs, defStyleAttr); }
    @Override protected void onAttachedToWindow(){super.onAttachedToWindow();post(this::finalizeUiLayout);}
    private void finalizeUiLayout(){
        View root=getRootView(); View log=root.findViewById(R.id.logScroll);
        if(log!=null){View p=log.getParent() instanceof View?(View)log.getParent():null;View c=p!=null&&p.getParent() instanceof View?(View)p.getParent():null;View card=c!=null&&c.getParent() instanceof View?(View)c.getParent():null;if(card!=null){ViewGroup.LayoutParams lp=card.getLayoutParams();lp.height=dp(600);card.setLayoutParams(lp);}}
        View tools=root.findViewById(R.id.toolsFabMenu);
        if(!arranged&&tools!=null&&tools.getParent() instanceof FrameLayout&&getParent() instanceof ViewGroup){FrameLayout frame=(FrameLayout)tools.getParent();ViewGroup old=(ViewGroup)getParent();old.removeView(this);frame.removeView(tools);LinearLayout stack=new LinearLayout(getContext());stack.setOrientation(LinearLayout.VERTICAL);stack.setGravity(Gravity.END);FrameLayout.LayoutParams slp=new FrameLayout.LayoutParams(-2,-2,Gravity.END|Gravity.BOTTOM);slp.rightMargin=dp(4);slp.bottomMargin=dp(4);frame.addView(stack,slp);stack.addView(tools,new LinearLayout.LayoutParams(-2,-2));LinearLayout.LayoutParams rlp=new LinearLayout.LayoutParams(dp(148),dp(62));rlp.topMargin=dp(8);stack.addView(this,rlp);setElevation(dp(4));arranged=true;}
        View theme=root.findViewById(R.id.headerThemeToggle);if(theme!=null){ViewGroup.LayoutParams lp=theme.getLayoutParams();lp.width=dp(58);lp.height=dp(58);theme.setLayoutParams(lp);theme.setTranslationY(-dp(2));}
        View nav=root.findViewById(R.id.bottomNav);if(nav instanceof ViewGroup){nav.setBackgroundResource(R.drawable.bg_bottom_nav);for(int i=0;i<((ViewGroup)nav).getChildCount();i++)if(((ViewGroup)nav).getChildAt(i) instanceof MaterialButton){MaterialButton b=(MaterialButton)((ViewGroup)nav).getChildAt(i);b.setBackgroundTintList(ColorStateList.valueOf(android.graphics.Color.TRANSPARENT));b.setCornerRadius(0);}}
        installClearHistory();
    }
    private void installClearHistory(){View root=getRootView();if(!(root instanceof ViewGroup)||root.findViewById(R.id.clearHistoryButton)!=null)return;HistoryClearButton clear=new HistoryClearButton(getContext());clear.setId(R.id.clearHistoryButton);FrameLayout host=root.findViewById(R.id.pageHost);if(host==null)return;FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(-2,dp(48),Gravity.END|Gravity.BOTTOM);lp.setMargins(0,0,dp(20),dp(16));host.addView(clear,lp);}
    @Override public boolean performClick(){if(confirmedClick){confirmedClick=false;return super.performClick();}ManagerCompatibility.Result r=ManagerCompatibility.evaluate(getContext());if(!r.canRun()){showBlocked(r);return true;}showConfirmation(r);return true;}
    private void showBlocked(ManagerCompatibility.Result r){Dialog d=createDialog();LinearLayout box=box();TextView t=text(20,true);t.setText(blockTitle(r));box.addView(t,margin(-1,-2,0,0,0,7));TextView m=text(13,false);m.setText(blockMessage(r));m.setLineSpacing(0,1.08f);box.addView(m,margin(-1,-2,0,0,0,16));if(r.state==ManagerCompatibility.State.MANAGER_REQUIRED){MaterialButton i=actionButton("Install supported manager",true);i.setOnClickListener(v->{d.dismiss();showManagerPicker();});box.addView(i,margin(-1,dp(54),0,0,0,14));}MaterialButton close=actionButton("Close",false);close.setOnClickListener(v->d.dismiss());box.addView(close,margin(-1,dp(48),0,0,0,0));show(d,box);}
    private void showConfirmation(ManagerCompatibility.Result r){Dialog d=createDialog();LinearLayout box=box();TextView t=text(20,true);t.setText("Run GhostLock");box.addView(t,margin(-1,-2,0,0,0,4));TextView s=text(12,false);s.setText("Execute kernel exploit & runtime");box.addView(s,margin(-1,-2,0,0,0,16));LinearLayout info=new LinearLayout(getContext());info.setOrientation(LinearLayout.VERTICAL);info.setBackground(round(color(R.color.surface_container_low),16));info.setPadding(dp(12),dp(10),dp(12),dp(10));info.addView(infoRow("Kernel",r.kernelSupported?"Kernel supported":"Kernel unsupported",r.kernelSupported?R.color.status_success:R.color.status_error),new LinearLayout.LayoutParams(-1,dp(44)));info.addView(infoRow("Manager",r.manager.name,R.color.text_primary),margin(-1,dp(44),0,7,0,0));info.addView(infoRow("Identity",r.manager.identityVerified?"Verified":"Recognized",r.manager.identityVerified?R.color.status_success:R.color.accent),margin(-1,dp(44),0,7,0,0));box.addView(info,margin(-1,-2,0,0,0,16));TextView m=text(12,false);m.setText("This operation will modify runtime state on the current device.");m.setLineSpacing(0,1.08f);box.addView(m,margin(-1,-2,0,0,0,16));LinearLayout actions=new LinearLayout(getContext());actions.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);MaterialButton cancel=actionButton("Cancel",false);cancel.setOnClickListener(v->d.dismiss());MaterialButton run=actionButton("Run",true);run.setOnClickListener(v->{d.dismiss();confirmedClick=true;performClick();});actions.addView(cancel,new LinearLayout.LayoutParams(-2,dp(48)));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-2,dp(48));rp.leftMargin=dp(8);actions.addView(run,rp);box.addView(actions,new LinearLayout.LayoutParams(-1,dp(52)));show(d,box);}
    private void showManagerPicker(){Dialog d=createDialog();LinearLayout box=box();TextView t=text(19,true);t.setText("Install supported manager");box.addView(t);TextView s=text(12,false);s.setText("Select a registered manager to continue.");box.addView(s,margin(-1,-2,0,6,0,14));for(ManagerCompatibility.ManagerInfo m:ManagerCompatibility.registeredManagers(getContext())){TextView row=text(14,true);row.setText(m.name+(m.installed?"  ·  Installed":"  ·  Not installed"));row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(16),0,dp(16),0);row.setMinHeight(dp(68));row.setBackground(round(color(R.color.surface_container_low),18));row.setClickable(true);row.setFocusable(true);row.setOnClickListener(v->{d.dismiss();ManagerCompatibility.openInstaller(getContext(),m);});box.addView(row,margin(-1,dp(68),0,0,0,10));}MaterialButton cancel=actionButton("Cancel",false);cancel.setOnClickListener(v->d.dismiss());box.addView(cancel,margin(-1,dp(48),0,4,0,0));show(d,box);}
    private LinearLayout infoRow(String label,String value,int cr){LinearLayout row=new LinearLayout(getContext());row.setGravity(Gravity.CENTER_VERTICAL);TextView l=text(12,true);l.setText(label);row.addView(l,new LinearLayout.LayoutParams(0,dp(44),1));TextView v=text(12,true);v.setText(value);v.setTextColor(color(cr));v.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);v.setMaxLines(1);row.addView(v,new LinearLayout.LayoutParams(-2,dp(44)));return row;}
    private String blockTitle(ManagerCompatibility.Result r){switch(r.state){case MANAGER_REQUIRED:return "Manager required";case KERNEL_UNSUPPORTED_MANAGER_REQUIRED:return "Kernel and manager unavailable";case SPOOFED_MANAGER:return "Manager identity mismatch";case UNSUPPORTED_MANAGER:return "Unsupported manager";default:return "Kernel unsupported";}}
    private String blockMessage(ManagerCompatibility.Result r){switch(r.state){case MANAGER_REQUIRED:return "The kernel is supported, but a registered manager is not installed.";case KERNEL_UNSUPPORTED_MANAGER_REQUIRED:return "The current kernel is not supported and no manager is installed. Installing a manager will not make this kernel compatible.";case SPOOFED_MANAGER:return "The detected manager identity is not trusted. Check the package and signing certificate before running GhostLock.";case UNSUPPORTED_MANAGER:return "The installed manager is not registered with GhostLock.";default:return "The current kernel does not provide the capability required by GhostLock.";}}
    private Dialog createDialog(){return new Dialog(getContext());}
    private LinearLayout box(){LinearLayout b=new LinearLayout(getContext());b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(22),dp(20),dp(22),dp(16));b.setBackground(round(color(R.color.surface_container),26));return b;}
    private void show(Dialog d,LinearLayout b){d.setContentView(b);d.show();if(d.getWindow()!=null){d.getWindow().setBackgroundDrawableResource(android.R.color.transparent);d.getWindow().setDimAmount(.60f);d.getWindow().addFlags(android.view.WindowManager.LayoutParams.FLAG_DIM_BEHIND);d.getWindow().setLayout((int)(getResources().getDisplayMetrics().widthPixels*.88f),-2);}}
    private MaterialButton actionButton(String s,boolean primary){MaterialButton b=new MaterialButton(getContext());b.setText(s);b.setAllCaps(false);b.setMinWidth(0);b.setTextSize(13);b.setBackgroundTintList(ColorStateList.valueOf(color(primary?R.color.accent:R.color.surface_container_low)));b.setTextColor(color(primary?R.color.on_accent:R.color.text_primary));return b;}
    private TextView text(int size,boolean bold){TextView v=new TextView(getContext());v.setTextSize(size);v.setTextColor(color(bold?R.color.text_primary:R.color.text_secondary));if(bold)v.setTypeface(null,android.graphics.Typeface.BOLD);return v;}
    private int color(int id){return ContextCompat.getColor(getContext(),id);}
    private LinearLayout.LayoutParams margin(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
    private GradientDrawable round(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
